DROP DATABASE IF EXISTS nhibernate;

CREATE DATABASE nhibernate;

USE nhibernate;
 
CREATE TABLE CLIENTE(

	ID INT(9) NOT NULL,

    NOME VARCHAR(50) NOT NULL,

    EMAIL VARCHAR(100) NOT NULL,

    SENHA VARCHAR(12) NOT NULL

);

ALTER TABLE CLIENTE

	ADD CONSTRAINT PK_CLIENTE_ID PRIMARY KEY (ID);

ALTER TABLE CLIENTE

	MODIFY COLUMN ID INT AUTO_INCREMENT;
 
CREATE TABLE PEDIDO (

	ID INT(9) NOT NULL,

    DATAPEDIDO DATE NOT NULL,

    IDCLIENTE INT(9) NOT NULL

);
 
ALTER TABLE PEDIDO

	ADD CONSTRAINT PK_PEDIDO_ID PRIMARY KEY (ID);
 
ALTER TABLE CLIENTE

	MODIFY COLUMN ID INT AUTO_INCREMENT;
 
ALTER TABLE PEDIDO

	ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (IDCLIENTE)

REFERENCES CLIENTE(ID);
 
CREATE TABLE PRODUTO (

	ID INT(9) NOT NULL,

    NOME VARCHAR(30) NOT NULL,

    PRECO FLOAT(6,2) NOT NULL

);
 
ALTER TABLE PRODUTO

	ADD CONSTRAINT PK_PRODUTO_ID PRIMARY KEY (ID);
 
ALTER TABLE PRODUTO

	MODIFY COLUMN ID INT AUTO_INCREMENT;

CREATE TABLE ITEMPRODUTO (

	ID INT(9) NOT NULL,

    IDPEDIDO INT(9) NOT NULL,

    IDPRODUTO INT(9) NOT NULL

);
 
ALTER TABLE ITEMPRODUTO

	ADD CONSTRAINT PK_ITEMPRODUTO_ID PRIMARY KEY (ID);
 
ALTER TABLE CLIENTE

	MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE ITEMPRODUTO

	ADD CONSTRAINT FK_PRODUTO_PEDIDO FOREIGN KEY (IDPEDIDO)

REFERENCES PEDIDO(ID);
 
ALTER TABLE ITEMPRODUTO

	ADD CONSTRAINT FK_PRODUTO_PRODUTO FOREIGN KEY (IDPRODUTO)

REFERENCES PRODUTO(ID);
 
SELECT * FROM CLIENTE;

SELECT * FROM PRODUTO;

SELECT * FROM PEDIDO;

SELECT * FROM ITEMPRODUTO;